name: Obfuscate JS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create dist folder
        run: mkdir dist

      - name: Copy project files
        run: cp -r *.js *.html *.css dist/ || true

      - name: Obfuscate JS
        run: npx javascript-obfuscator dist --output dist

      - name: Push to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build
